spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: root
      password: svip_mongodb
      authentication-database: admin
      database: svip
    redis:
      host: redis
      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/svip?useSSL=false
    username: root
    password: svip_mariadb
  mail:
    username: gorojack_mini
    email: gorojack_mini@163.com
    host: smtp.163.com
    protocol: smtps
    default-encoding: UTF-8
    port: 465
    password: OPSLHQVMDUYTGWAT
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
jwt:
  secret: superShop
  expiration: 3600
