spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: svip_mongodb
      authentication-database: admin
      database: svip
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/svip?useSSL=false
    username: root
    password: svip_mariadb
server:
  port: 8080
jwt:
  secret: superShop
  expiration: 3600
